### ISSUE TITLE
Reviews screen - Loading screen shows error in console

### ISSUE THREAD

**Issue by Luch76** [oci-labs/check-ins#2581]
**Describe the bug**
This error shows on the console window when loading the "Reviews" screen: 
Uncaught (in promise) TypeError: Cannot destructure property 'id' of 'I' as it is undefined.
    at index-osyma6T4.js:1422:16419
    at Array.map (<anonymous>)
    at _ (index-osyma6T4.js:1422:16402)

**To Reproduce**
Goto the Reviews screen and observe the console

**Comment by mkimberlin** [comment]
I tried this in [dev](https://checkins-develop-tuvcfzotpq-uc.a.run.app/feedback/reviews) and was unable to reproduce. Does this occur locally?

**Comment by timyates** [comment]
I tried and failed to reproduce this locally with the current develop branch 🤔 

I may be taking a different path, or be clicking the wrong things though, do you still see it (and if so, do you have a step by step reproducer)?

**Comment by Luch76** [comment]
Yes, I can still duplicate with the current develop branch. My steps: I drop my existing local Podman-database and re-create it (not neccessary, but just to show it happens with a "fresh start"),,, I then create a review and fill in the dates at the top,,, I then assign another member, "Mighty Baboon",,, and then navigate to home screen, and then when clicking back to the "reviews" screen, the error appears
